#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${API_BASE_URL:-}" ]]; then
  echo "错误：必须设置 API_BASE_URL。" >&2
  exit 1
fi

if [[ -z "${TEAM_ID:-}" ]]; then
  echo "错误：必须设置 TEAM_ID。" >&2
  exit 1
fi

if [[ ! "$TEAM_ID" =~ ^[A-Za-z0-9]+$ ]]; then
  echo "错误：TEAM_ID 只能包含字母和数字。" >&2
  exit 1
fi

# Release builds must name the product. ALLOW_DEFAULT_BRAND=1 is the explicit
# opt-in for the open-source bundle id app.luma.client and the Luma display name.
if [[ "${ALLOW_DEFAULT_BRAND:-}" != "1" ]]; then
  if [[ -z "${BUNDLE_ID:-}" ]]; then
    echo "错误：发布构建必须设置 BUNDLE_ID。若要使用开源默认 app.luma.client，请设置 ALLOW_DEFAULT_BRAND=1。" >&2
    exit 1
  fi
  if [[ "$BUNDLE_ID" == "app.luma.client" ]]; then
    echo "错误：BUNDLE_ID 不能使用开源默认 app.luma.client，除非设置 ALLOW_DEFAULT_BRAND=1。" >&2
    exit 1
  fi
  if [[ -z "${BRAND_DISPLAY_NAME:-}" ]]; then
    echo "错误：发布构建必须设置 BRAND_DISPLAY_NAME。" >&2
    exit 1
  fi
fi

validate_xcconfig_value() {
  local name="$1"
  local value="$2"
  if [[ "$value" == *$'\n'* || "$value" == *$'\r'* || "$value" == *'//'* ]]; then
    echo "错误：${name} 包含无法写入 xcconfig 的字符。" >&2
    exit 1
  fi
}

if [[ -n "${BRAND_DISPLAY_NAME:-}" ]]; then
  validate_xcconfig_value "BRAND_DISPLAY_NAME" "$BRAND_DISPLAY_NAME"
fi
if [[ -n "${BUNDLE_ID:-}" ]]; then
  validate_xcconfig_value "BUNDLE_ID" "$BUNDLE_ID"
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."

FLUTTER_BIN="$(command -v flutter)"
BUILD_NAME="$(awk '/^version:/ {split($2, version, "[+]"); print version[1]; exit}' pubspec.yaml)"
BUILD_NUMBER="${BUILD_NUMBER:-$(awk '/^version:/ {split($2, version, "[+]"); print version[2]; exit}' pubspec.yaml)}"
if [[ ! "$BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
  echo "错误：BUILD_NUMBER 必须是数字，或在 pubspec.yaml 的 version 中指定构建号。" >&2
  exit 1
fi

mkdir -p ios/Flutter
{
  echo "// Generated by scripts/build_ios_release.sh. Do not commit."
  if [[ -n "${BRAND_DISPLAY_NAME:-}" ]]; then
    printf 'BRAND_DISPLAY_NAME=%s\n' "$BRAND_DISPLAY_NAME"
  fi
  if [[ -n "${BUNDLE_ID:-}" ]]; then
    printf 'PRODUCT_BUNDLE_IDENTIFIER=%s\n' "$BUNDLE_ID"
  fi
  printf 'DEVELOPMENT_TEAM=%s\n' "$TEAM_ID"
} > ios/Flutter/Brand.local.xcconfig

cat > ios/ExportOptions.local.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>app-store-connect</string>
	<key>teamID</key>
	<string>${TEAM_ID}</string>
	<key>signingStyle</key>
	<string>automatic</string>
	<key>uploadSymbols</key>
	<true/>
	<key>destination</key>
	<string>export</string>
</dict>
</plist>
EOF

args=(
  build
  ipa
  --release
  "--dart-define=API_BASE_URL=$API_BASE_URL"
  "--dart-define=APP_VERSION=$BUILD_NAME+$BUILD_NUMBER"
)
if [[ -n "${BRAND_DISPLAY_NAME:-}" ]]; then
  args+=("--dart-define=BRAND_PRODUCT_NAME=$BRAND_DISPLAY_NAME")
fi
args+=(
  "--build-number=$BUILD_NUMBER"
  --export-options-plist=ios/ExportOptions.local.plist
)

exec "$FLUTTER_BIN" "${args[@]}"
