"""Pluggable file storage backends.

The application stores only a logical ``storage`` name and ``storage_key`` in
its database.  Backend implementations below deliberately keep provider
addresses and credentials on the server side; callers never receive a remote
URL.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os
import tempfile
import threading
import time
from pathlib import Path
from typing import Any, BinaryIO, Dict, Iterator, Optional, Protocol, Tuple
from urllib.parse import urlparse

import httpx

try:  # Optional at import time; required only when COS is selected.
    import qcloud_cos  # type: ignore
except ImportError:  # pragma: no cover - optional dependency guard
    qcloud_cos = None  # type: ignore

logger = logging.getLogger(__name__)

CHUNK_SIZE = 1024 * 1024


class Storage(Protocol):
    """Common interface implemented by all file stores."""

    name: str

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        ...

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        ...

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        ...

    def delete(self, storage_key: str) -> None:
        ...


class StorageConfigurationError(RuntimeError):
    """A selected backend is missing required configuration."""


class StorageUnavailable(RuntimeError):
    """A backend recorded by a file row cannot currently be configured."""


def _safe_key(key: str) -> str:
    """Validate a relative storage key before using it as a local path."""

    if not isinstance(key, str) or not key or "\x00" in key:
        raise ValueError("invalid storage key")
    # Keys are generated by the service and must remain POSIX relative paths.
    if key.startswith("/") or any(part in ("", ".", "..") for part in key.replace("\\", "/").split("/")):
        raise ValueError("invalid storage key")
    return key.replace("\\", "/")


def _read_limited(stream: BinaryIO, max_bytes: Optional[int]) -> bytes:
    if max_bytes is not None and max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    out = bytearray()
    while True:
        amount = CHUNK_SIZE if max_bytes is None else min(CHUNK_SIZE, max_bytes - len(out))
        if amount <= 0:
            break
        chunk = stream.read(amount)
        if not chunk:
            break
        out.extend(chunk)
    return bytes(out)


def _collect_limited(iterator: Iterator[bytes], max_bytes: Optional[int]) -> bytes:
    """Collect a backend stream while closing it on an early byte limit.

    ``open_stream`` implementations hold an open file/HTTP response until
    their generator is closed.  Explicitly closing here avoids keeping a
    remote connection alive when bounded text extraction only needs a prefix.
    """

    if max_bytes is not None and max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    if max_bytes == 0:
        close = getattr(iterator, "close", None)
        if callable(close):
            close()
        return b""
    out = bytearray()
    try:
        for chunk in iterator:
            if max_bytes is None:
                out.extend(chunk)
                continue
            remaining = max_bytes - len(out)
            if remaining <= 0:
                break
            out.extend(chunk[:remaining])
            if len(chunk) >= remaining:
                break
    finally:
        close = getattr(iterator, "close", None)
        if callable(close):
            close()
    return bytes(out)


class LocalStorage:
    name = "local"

    def __init__(self, root: Optional[str] = None) -> None:
        if root is None:
            root = os.getenv("ASSISTANT_FILE_ROOT", str(Path(__file__).resolve().parents[1] / "data" / "files"))
        self.root = Path(root).expanduser().resolve()

    def _path(self, storage_key: str) -> Path:
        key = _safe_key(storage_key)
        candidate = (self.root / key).resolve()
        try:
            candidate.relative_to(self.root)
        except ValueError as exc:
            raise ValueError("invalid storage key") from exc
        return candidate

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        del size, content_type
        destination = self._path(key_hint)
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            os.chmod(self.root, 0o700)
        except OSError:
            pass
        try:
            os.chmod(destination.parent, 0o700)
        except OSError:
            pass
        # Write and replace atomically so readers never observe a partial file.
        fd, temp_name = tempfile.mkstemp(prefix=".upload-", dir=str(destination.parent))
        try:
            with os.fdopen(fd, "wb") as handle:
                while True:
                    chunk = fileobj.read(CHUNK_SIZE)
                    if not chunk:
                        break
                    handle.write(chunk)
                handle.flush()
                try:
                    os.fsync(handle.fileno())
                except OSError:
                    pass
            os.chmod(temp_name, 0o600)
            os.replace(temp_name, destination)
        except Exception:
            try:
                os.unlink(temp_name)
            except OSError:
                pass
            raise
        return _safe_key(key_hint)

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        path = self._path(storage_key)

        def iterator() -> Iterator[bytes]:
            try:
                with path.open("rb") as handle:
                    while True:
                        chunk = handle.read(CHUNK_SIZE)
                        if not chunk:
                            break
                        yield chunk
            except FileNotFoundError:
                raise

        return iterator()

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        with self._path(storage_key).open("rb") as handle:
            return _read_limited(handle, max_bytes)

    def delete(self, storage_key: str) -> None:
        try:
            self._path(storage_key).unlink()
        except FileNotFoundError:
            return


class COSStorage:
    name = "cos"

    def __init__(
        self,
        secret_id: Optional[str] = None,
        secret_key: Optional[str] = None,
        region: Optional[str] = None,
        bucket: Optional[str] = None,
        prefix: Optional[str] = None,
        client: Any = None,
    ) -> None:
        self.secret_id = secret_id if secret_id is not None else os.getenv("COS_SECRET_ID", "").strip()
        self.secret_key = secret_key if secret_key is not None else os.getenv("COS_SECRET_KEY", "").strip()
        self.region = region if region is not None else os.getenv("COS_REGION", "ap-shanghai").strip() or "ap-shanghai"
        self.bucket = bucket if bucket is not None else os.getenv("COS_BUCKET", "").strip()
        raw_prefix = prefix if prefix is not None else os.getenv("COS_PREFIX", "luma/")
        self.prefix = (raw_prefix or "").strip().lstrip("/")
        if self.prefix and not self.prefix.endswith("/"):
            self.prefix += "/"
        if client is None:
            if qcloud_cos is None:  # pragma: no cover - dependency guard
                raise StorageConfigurationError("COSStorage 需要安装 cos-python-sdk-v5")
            config = qcloud_cos.CosConfig(Region=self.region, SecretId=self.secret_id, SecretKey=self.secret_key, Scheme="https")
            client = qcloud_cos.CosS3Client(config)
        self.client = client

    @classmethod
    def from_env(cls) -> "COSStorage":
        missing = [name for name in ("COS_SECRET_ID", "COS_SECRET_KEY", "COS_BUCKET") if not os.getenv(name, "").strip()]
        if missing:
            raise StorageConfigurationError("COS 存储缺少配置变量: " + ", ".join(missing))
        return cls()

    def _remote_key(self, storage_key: str) -> str:
        return self.prefix + _safe_key(storage_key)

    @staticmethod
    def _is_not_found(exc: BaseException) -> bool:
        status = getattr(exc, "status_code", None)
        if status is None:
            getter = getattr(exc, "get_status_code", None)
            if callable(getter):
                try:
                    status = getter()
                except Exception:
                    status = None
        code_value = getattr(exc, "error_code", getattr(exc, "code", ""))
        if not code_value:
            getter = getattr(exc, "get_error_code", None)
            if callable(getter):
                try:
                    code_value = getter()
                except Exception:
                    code_value = ""
        code = str(code_value)
        return str(status) == "404" or code in {"NoSuchKey", "NoSuchObject", "404", "NotFound"}

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        key = _safe_key(key_hint)
        kwargs = {
            "Bucket": self.bucket,
            "Key": self._remote_key(key),
            "Body": fileobj,
            "ContentLength": size,
            "ContentType": content_type or "application/octet-stream",
            "ServerSideEncryption": "AES256",
        }
        self.client.put_object(**kwargs)
        return key

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        key = self._remote_key(storage_key)

        def iterator() -> Iterator[bytes]:
            try:
                response = self.client.get_object(Bucket=self.bucket, Key=key)
            except Exception as exc:
                if self._is_not_found(exc):
                    raise FileNotFoundError(storage_key) from exc
                raise
            body = response.get("Body") if isinstance(response, dict) else getattr(response, "Body", response)
            raw_stream = getattr(body, "get_raw_stream", None)
            source = raw_stream() if callable(raw_stream) else body
            try:
                while True:
                    chunk = source.read(CHUNK_SIZE)
                    if not chunk:
                        break
                    yield chunk
            finally:
                close = getattr(source, "close", None)
                if callable(close):
                    close()

        return iterator()

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        return _collect_limited(self.open_stream(storage_key), max_bytes)

    def delete(self, storage_key: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=self._remote_key(storage_key))
        except Exception as exc:
            if self._is_not_found(exc):
                return
            raise


_http_client: Optional[httpx.Client] = None
_http_client_lock = threading.RLock()


def _shared_http_client(timeout: float) -> httpx.Client:
    global _http_client
    with _http_client_lock:
        if _http_client is None:
            _http_client = httpx.Client(timeout=timeout, follow_redirects=False)
        return _http_client


def _positive_id(value: Any) -> int:
    if isinstance(value, bool):
        raise ValueError("invalid remote file id")
    if isinstance(value, int):
        result = value
    elif isinstance(value, str) and value.isdigit():
        result = int(value)
    else:
        raise ValueError("invalid remote file id")
    if result <= 0:
        raise ValueError("invalid remote file id")
    return result


class FileServiceStorage:
    name = "fileservice"

    def __init__(
        self,
        base_url: Optional[str] = None,
        app_key: Optional[str] = None,
        app_secret: Optional[str] = None,
        folder_id: Optional[str] = None,
        timeout: Optional[float] = None,
        client: Optional[httpx.Client] = None,
    ) -> None:
        self.base_url = (base_url if base_url is not None else os.getenv("FILE_SERVICE_URL", "")).strip().rstrip("/")
        self.app_key = (app_key if app_key is not None else os.getenv("FILE_SERVICE_APP_KEY", "")).strip()
        self.app_secret = (app_secret if app_secret is not None else os.getenv("FILE_SERVICE_APP_SECRET", "")).strip()
        self.folder_id = (folder_id if folder_id is not None else os.getenv("FILE_SERVICE_FOLDER_ID", "")).strip()
        if timeout is None:
            try:
                timeout = float(os.getenv("FILE_SERVICE_TIMEOUT", "60"))
            except (TypeError, ValueError):
                timeout = 60.0
        self.timeout = max(0.1, float(timeout))
        self._validate_url()
        self.client = client or _shared_http_client(self.timeout)

    @classmethod
    def from_env(cls) -> "FileServiceStorage":
        missing = [name for name in ("FILE_SERVICE_URL", "FILE_SERVICE_APP_KEY", "FILE_SERVICE_APP_SECRET") if not os.getenv(name, "").strip()]
        if missing:
            raise StorageConfigurationError("FileService 存储缺少配置变量: " + ", ".join(missing))
        return cls()

    def _validate_url(self) -> None:
        if not self.base_url:
            raise StorageConfigurationError("FileService 存储缺少配置变量: FILE_SERVICE_URL")
        parsed = urlparse(self.base_url)
        if parsed.username or parsed.password:
            raise StorageConfigurationError("FILE_SERVICE_URL 不能包含用户名或密码")
        allow_http = os.getenv("FILE_SERVICE_ALLOW_HTTP", "false").strip().lower() == "true"
        if parsed.scheme != "https" and not (allow_http and parsed.scheme == "http"):
            raise StorageConfigurationError("FILE_SERVICE_URL 必须使用 https；本地开发可设置 FILE_SERVICE_ALLOW_HTTP=true")
        if not parsed.netloc:
            raise StorageConfigurationError("FILE_SERVICE_URL 格式无效")

    def _headers(self) -> Dict[str, str]:
        timestamp = str(int(time.time() * 1000))
        signature = base64.b64encode(hmac.new(self.app_secret.encode("utf-8"), timestamp.encode("utf-8"), hashlib.sha256).digest()).decode("ascii")
        return {"X-App-Key": self.app_key, "X-Timestamp": timestamp, "X-Signature": signature}

    @staticmethod
    def _status_error(method: str, status: int, elapsed: float) -> RuntimeError:
        logger.warning("FileService %s status=%s elapsed_ms=%.1f", method, status, elapsed * 1000)
        return RuntimeError("FileService 请求失败")

    def _json_success(self, response: httpx.Response, method: str, started: float) -> Dict[str, Any]:
        elapsed = time.monotonic() - started
        logger.info("FileService %s status=%s elapsed_ms=%.1f", method, response.status_code, elapsed * 1000)
        if response.status_code < 200 or response.status_code >= 300:
            raise self._status_error(method, response.status_code, elapsed)
        try:
            payload = response.json()
        except Exception:
            raise RuntimeError("FileService 响应格式无效") from None
        if not isinstance(payload, dict) or type(payload.get("code")) is not int or payload.get("code") != 0:
            raise RuntimeError("FileService 响应失败")
        return payload

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        key = _safe_key(key_hint)
        file_id = key.rsplit("/", 1)[-1]
        data: Dict[str, str] = {}
        if self.folder_id:
            data["folder_id"] = self.folder_id
        files = {"file": (file_id, fileobj, content_type or "application/octet-stream")}
        started = time.monotonic()
        try:
            response = self.client.post(
                self.base_url + "/api/fs/files/upload",
                headers=self._headers(),
                data=data,
                files=files,
                timeout=self.timeout,
                follow_redirects=False,
            )
            payload = self._json_success(response, "POST /api/fs/files/upload", started)
            remote_id = _positive_id((payload.get("data") or {}).get("id") if isinstance(payload.get("data"), dict) else None)
            logger.info("FileService POST /api/fs/files/upload id=%s status=%s elapsed_ms=%.1f", remote_id, response.status_code, (time.monotonic() - started) * 1000)
            return "fs:" + str(remote_id)
        except (StorageConfigurationError, ValueError):
            raise
        except RuntimeError:
            raise
        except Exception:
            # Do not retain the transport exception as a chained cause: a
            # custom HTTP client can include request headers in its message.
            raise RuntimeError("FileService 上传失败") from None

    def _remote_id(self, storage_key: str) -> int:
        if not isinstance(storage_key, str) or not storage_key.startswith("fs:"):
            raise ValueError("invalid FileService storage key")
        return _positive_id(storage_key[3:])

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        remote_id = self._remote_id(storage_key)
        url = self.base_url + "/api/fs/files/{}/download".format(remote_id)

        def iterator() -> Iterator[bytes]:
            started = time.monotonic()
            try:
                with self.client.stream(
                    "GET", url, headers=self._headers(), timeout=self.timeout, follow_redirects=False
                ) as response:
                    elapsed = time.monotonic() - started
                    logger.info("FileService GET /api/fs/files/%s/download status=%s elapsed_ms=%.1f", remote_id, response.status_code, elapsed * 1000)
                    if response.status_code == 404:
                        raise FileNotFoundError(storage_key)
                    if response.status_code < 200 or response.status_code >= 300:
                        raise self._status_error("GET /api/fs/files/{}/download".format(remote_id), response.status_code, elapsed)
                    for chunk in response.iter_bytes(CHUNK_SIZE):
                        if chunk:
                            yield chunk
            except FileNotFoundError:
                raise
            except RuntimeError:
                raise
            except Exception:
                raise RuntimeError("FileService 下载失败") from None

        return iterator()

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        return _collect_limited(self.open_stream(storage_key), max_bytes)

    def delete(self, storage_key: str) -> None:
        remote_id = self._remote_id(storage_key)
        started = time.monotonic()
        try:
            response = self.client.delete(
                self.base_url + "/api/fs/files/{}".format(remote_id),
                headers=self._headers(),
                timeout=self.timeout,
                follow_redirects=False,
            )
            elapsed = time.monotonic() - started
            logger.info("FileService DELETE /api/fs/files/%s status=%s elapsed_ms=%.1f", remote_id, response.status_code, elapsed * 1000)
            if response.status_code == 404:
                return
            if response.status_code < 200 or response.status_code >= 300:
                raise self._status_error("DELETE /api/fs/files/{}".format(remote_id), response.status_code, elapsed)
            # Delete responses use the common envelope when present.  Avoid
            # logging or propagating its contents.
            if response.content:
                try:
                    payload = response.json()
                except Exception:
                    raise RuntimeError("FileService 响应格式无效") from None
                if not isinstance(payload, dict) or type(payload.get("code")) is not int or payload.get("code") != 0:
                    raise RuntimeError("FileService 删除失败")
        except RuntimeError:
            raise
        except Exception:
            raise RuntimeError("FileService 删除失败") from None


_storage_cache: Dict[str, Tuple[str, Storage]] = {}
_storage_cache_lock = threading.RLock()


def _config_signature(name: str) -> str:
    names = {
        "local": ("ASSISTANT_FILE_ROOT",),
        "cos": ("COS_SECRET_ID", "COS_SECRET_KEY", "COS_REGION", "COS_BUCKET", "COS_PREFIX"),
        "fileservice": ("FILE_SERVICE_URL", "FILE_SERVICE_APP_KEY", "FILE_SERVICE_APP_SECRET", "FILE_SERVICE_FOLDER_ID", "FILE_SERVICE_TIMEOUT", "FILE_SERVICE_ALLOW_HTTP"),
    }[name]
    return "\x00".join(os.getenv(item, "") for item in names)


def clear_storage_cache() -> None:
    with _storage_cache_lock:
        _storage_cache.clear()


def get_storage(name: Optional[str] = None) -> Storage:
    backend = (name or os.getenv("FILE_STORAGE", "local")).strip().lower() or "local"
    if backend not in {"local", "cos", "fileservice"}:
        raise StorageConfigurationError("FILE_STORAGE 必须是 local、cos 或 fileservice")
    signature = _config_signature(backend)
    with _storage_cache_lock:
        cached = _storage_cache.get(backend)
        if cached is not None and cached[0] == signature:
            return cached[1]
        if backend == "local":
            instance: Storage = LocalStorage()
        elif backend == "cos":
            instance = COSStorage.from_env()
        else:
            instance = FileServiceStorage.from_env()
        _storage_cache[backend] = (signature, instance)
        return instance


def storage_for_row(row: Any) -> Storage:
    """Resolve a backend from a file row's recorded ``storage`` column."""

    name = str(row.get("storage") if hasattr(row, "get") else "")
    if name not in {"local", "cos", "fileservice"}:
        raise StorageUnavailable("文件存储后端不可用")
    try:
        return get_storage(name)
    except StorageConfigurationError as exc:
        raise StorageUnavailable("文件存储后端不可用") from exc


# Compatibility aliases used by services and tests.
get_storage_for_row = storage_for_row
build_storage = get_storage
reset_storage_cache = clear_storage_cache
