"""Pluggable file storage backends.

The application stores only a logical ``storage`` name and ``storage_key`` in
its database.  Backend implementations below deliberately keep provider
addresses and credentials on the server side; callers never receive a remote
URL.

Built-in backends are ``local`` and ``cos``. Additional backends register
through :class:`StorageRegistry`; ``FILE_STORAGE`` and each file row's
``storage`` column are looked up there.
"""

from __future__ import annotations

import os
import re
import tempfile
import threading
from pathlib import Path
from typing import Any, BinaryIO, Callable, Dict, Iterator, Optional, Protocol, Sequence, Tuple

try:  # Optional at import time; required only when COS is selected.
    import qcloud_cos  # type: ignore
except ImportError:  # pragma: no cover - optional dependency guard
    qcloud_cos = None  # type: ignore

CHUNK_SIZE = 1024 * 1024
_BACKEND_NAME = re.compile(r"[a-z][a-z0-9_-]{0,31}")


class Storage(Protocol):
    """Common interface implemented by all file stores."""

    name: str

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        ...

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        ...

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        ...

    def delete(self, storage_key: str) -> None:
        ...


class StorageConfigurationError(RuntimeError):
    """A selected backend is missing required configuration."""


class StorageUnavailable(RuntimeError):
    """A backend recorded by a file row cannot currently be configured."""


def _safe_key(key: str) -> str:
    """Validate a relative storage key before using it as a local path."""

    if not isinstance(key, str) or not key or "\x00" in key:
        raise ValueError("invalid storage key")
    # Keys are generated by the service and must remain POSIX relative paths.
    if key.startswith("/") or any(part in ("", ".", "..") for part in key.replace("\\", "/").split("/")):
        raise ValueError("invalid storage key")
    return key.replace("\\", "/")


def _read_limited(stream: BinaryIO, max_bytes: Optional[int]) -> bytes:
    if max_bytes is not None and max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    out = bytearray()
    while True:
        amount = CHUNK_SIZE if max_bytes is None else min(CHUNK_SIZE, max_bytes - len(out))
        if amount <= 0:
            break
        chunk = stream.read(amount)
        if not chunk:
            break
        out.extend(chunk)
    return bytes(out)


def _collect_limited(iterator: Iterator[bytes], max_bytes: Optional[int]) -> bytes:
    """Collect a backend stream while closing it on an early byte limit.

    ``open_stream`` implementations hold an open file/HTTP response until
    their generator is closed.  Explicitly closing here avoids keeping a
    remote connection alive when bounded text extraction only needs a prefix.
    """

    if max_bytes is not None and max_bytes < 0:
        raise ValueError("max_bytes must be non-negative")
    if max_bytes == 0:
        close = getattr(iterator, "close", None)
        if callable(close):
            close()
        return b""
    out = bytearray()
    try:
        for chunk in iterator:
            if max_bytes is None:
                out.extend(chunk)
                continue
            remaining = max_bytes - len(out)
            if remaining <= 0:
                break
            out.extend(chunk[:remaining])
            if len(chunk) >= remaining:
                break
    finally:
        close = getattr(iterator, "close", None)
        if callable(close):
            close()
    return bytes(out)


class LocalStorage:
    name = "local"

    def __init__(self, root: Optional[str] = None) -> None:
        if root is None:
            root = os.getenv("ASSISTANT_FILE_ROOT", str(Path(__file__).resolve().parents[1] / "data" / "files"))
        self.root = Path(root).expanduser().resolve()

    def _path(self, storage_key: str) -> Path:
        key = _safe_key(storage_key)
        candidate = (self.root / key).resolve()
        try:
            candidate.relative_to(self.root)
        except ValueError as exc:
            raise ValueError("invalid storage key") from exc
        return candidate

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        del size, content_type
        destination = self._path(key_hint)
        destination.parent.mkdir(parents=True, exist_ok=True)
        try:
            os.chmod(self.root, 0o700)
        except OSError:
            pass
        try:
            os.chmod(destination.parent, 0o700)
        except OSError:
            pass
        # Write and replace atomically so readers never observe a partial file.
        fd, temp_name = tempfile.mkstemp(prefix=".upload-", dir=str(destination.parent))
        try:
            with os.fdopen(fd, "wb") as handle:
                while True:
                    chunk = fileobj.read(CHUNK_SIZE)
                    if not chunk:
                        break
                    handle.write(chunk)
                handle.flush()
                try:
                    os.fsync(handle.fileno())
                except OSError:
                    pass
            os.chmod(temp_name, 0o600)
            os.replace(temp_name, destination)
        except Exception:
            try:
                os.unlink(temp_name)
            except OSError:
                pass
            raise
        return _safe_key(key_hint)

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        path = self._path(storage_key)

        def iterator() -> Iterator[bytes]:
            try:
                with path.open("rb") as handle:
                    while True:
                        chunk = handle.read(CHUNK_SIZE)
                        if not chunk:
                            break
                        yield chunk
            except FileNotFoundError:
                raise

        return iterator()

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        with self._path(storage_key).open("rb") as handle:
            return _read_limited(handle, max_bytes)

    def delete(self, storage_key: str) -> None:
        try:
            self._path(storage_key).unlink()
        except FileNotFoundError:
            return


class COSStorage:
    name = "cos"

    def __init__(
        self,
        secret_id: Optional[str] = None,
        secret_key: Optional[str] = None,
        region: Optional[str] = None,
        bucket: Optional[str] = None,
        prefix: Optional[str] = None,
        client: Any = None,
    ) -> None:
        self.secret_id = secret_id if secret_id is not None else os.getenv("COS_SECRET_ID", "").strip()
        self.secret_key = secret_key if secret_key is not None else os.getenv("COS_SECRET_KEY", "").strip()
        self.region = (region if region is not None else os.getenv("COS_REGION", "")).strip()
        if not self.region:
            raise StorageConfigurationError("COS 存储缺少配置变量: COS_REGION")
        self.bucket = bucket if bucket is not None else os.getenv("COS_BUCKET", "").strip()
        raw_prefix = prefix if prefix is not None else os.getenv("COS_PREFIX", "luma/")
        self.prefix = (raw_prefix or "").strip().lstrip("/")
        if self.prefix and not self.prefix.endswith("/"):
            self.prefix += "/"
        if client is None:
            if qcloud_cos is None:  # pragma: no cover - dependency guard
                raise StorageConfigurationError("COSStorage 需要安装 cos-python-sdk-v5")
            config = qcloud_cos.CosConfig(Region=self.region, SecretId=self.secret_id, SecretKey=self.secret_key, Scheme="https")
            client = qcloud_cos.CosS3Client(config)
        self.client = client

    @classmethod
    def from_env(cls) -> "COSStorage":
        missing = [name for name in ("COS_SECRET_ID", "COS_SECRET_KEY", "COS_BUCKET", "COS_REGION") if not os.getenv(name, "").strip()]
        if missing:
            raise StorageConfigurationError("COS 存储缺少配置变量: " + ", ".join(missing))
        return cls()

    def _remote_key(self, storage_key: str) -> str:
        return self.prefix + _safe_key(storage_key)

    @staticmethod
    def _is_not_found(exc: BaseException) -> bool:
        status = getattr(exc, "status_code", None)
        if status is None:
            getter = getattr(exc, "get_status_code", None)
            if callable(getter):
                try:
                    status = getter()
                except Exception:
                    status = None
        code_value = getattr(exc, "error_code", getattr(exc, "code", ""))
        if not code_value:
            getter = getattr(exc, "get_error_code", None)
            if callable(getter):
                try:
                    code_value = getter()
                except Exception:
                    code_value = ""
        code = str(code_value)
        return str(status) == "404" or code in {"NoSuchKey", "NoSuchObject", "404", "NotFound"}

    def put(self, key_hint: str, fileobj: BinaryIO, size: int, content_type: str) -> str:
        key = _safe_key(key_hint)
        kwargs = {
            "Bucket": self.bucket,
            "Key": self._remote_key(key),
            "Body": fileobj,
            "ContentLength": size,
            "ContentType": content_type or "application/octet-stream",
            "ServerSideEncryption": "AES256",
        }
        self.client.put_object(**kwargs)
        return key

    def open_stream(self, storage_key: str) -> Iterator[bytes]:
        key = self._remote_key(storage_key)

        def iterator() -> Iterator[bytes]:
            try:
                response = self.client.get_object(Bucket=self.bucket, Key=key)
            except Exception as exc:
                if self._is_not_found(exc):
                    raise FileNotFoundError(storage_key) from exc
                raise
            body = response.get("Body") if isinstance(response, dict) else getattr(response, "Body", response)
            raw_stream = getattr(body, "get_raw_stream", None)
            source = raw_stream() if callable(raw_stream) else body
            try:
                while True:
                    chunk = source.read(CHUNK_SIZE)
                    if not chunk:
                        break
                    yield chunk
            finally:
                close = getattr(source, "close", None)
                if callable(close):
                    close()

        return iterator()

    def get(self, storage_key: str, max_bytes: Optional[int] = None) -> bytes:
        return _collect_limited(self.open_stream(storage_key), max_bytes)

    def delete(self, storage_key: str) -> None:
        try:
            self.client.delete_object(Bucket=self.bucket, Key=self._remote_key(storage_key))
        except Exception as exc:
            if self._is_not_found(exc):
                return
            raise


class _StorageBackend:
    def __init__(self, name: str, factory: Callable[[], Storage], config_keys: Sequence[str], builtin: bool) -> None:
        self.name = name
        self.factory = factory
        self.config_keys = tuple(config_keys)
        self.builtin = builtin


class StorageRegistry:
    """Named storage factories. Built-ins cannot be replaced by a plugin."""

    def __init__(self) -> None:
        self._backends: Dict[str, _StorageBackend] = {}
        self._plugin_names: set = set()

    def register(self, name: str, factory: Callable[[], Storage], config_keys: Sequence[str] = (), *, builtin: bool = False) -> None:
        key = _normalize_backend_name(name)
        if not key:
            raise StorageConfigurationError("存储后端名称无效")
        if not callable(factory):
            raise StorageConfigurationError("存储后端缺少构造函数")
        existing = self._backends.get(key)
        if existing is not None and existing.builtin and not builtin:
            raise StorageConfigurationError("不能覆盖内置存储后端: " + key)
        if existing is not None and not builtin:
            raise StorageConfigurationError("存储后端已注册: " + key)
        self._backends[key] = _StorageBackend(key, factory, config_keys, builtin)
        if not builtin:
            self._plugin_names.add(key)

    def unregister_plugins(self) -> None:
        for name in list(self._plugin_names):
            self._backends.pop(name, None)
        self._plugin_names.clear()

    def get(self, name: str) -> Optional[_StorageBackend]:
        key = _normalize_backend_name(name)
        if not key:
            return None
        return self._backends.get(key)

    def names(self) -> Tuple[str, ...]:
        return tuple(self._backends)


def _normalize_backend_name(name: Any) -> str:
    key = str(name or "").strip().lower()
    if _BACKEND_NAME.fullmatch(key):
        return key
    return ""


def _local_factory() -> LocalStorage:
    return LocalStorage()


storage_registry = StorageRegistry()
storage_registry.register("local", _local_factory, ("ASSISTANT_FILE_ROOT",), builtin=True)
storage_registry.register(
    "cos",
    COSStorage.from_env,
    ("COS_SECRET_ID", "COS_SECRET_KEY", "COS_REGION", "COS_BUCKET", "COS_PREFIX"),
    builtin=True,
)


_storage_cache: Dict[str, Tuple[str, Storage]] = {}
_storage_cache_lock = threading.RLock()


def clear_storage_cache() -> None:
    with _storage_cache_lock:
        _storage_cache.clear()


def get_storage(name: Optional[str] = None) -> Storage:
    raw = name if name is not None else os.getenv("FILE_STORAGE", "local")
    backend = _normalize_backend_name(raw)
    if not backend:
        raise StorageConfigurationError("未注册的存储后端")
    spec = storage_registry.get(backend)
    if spec is None:
        raise StorageConfigurationError("未注册的存储后端: " + backend)
    signature = "\x00".join(os.getenv(item, "") for item in spec.config_keys)
    with _storage_cache_lock:
        cached = _storage_cache.get(backend)
        if cached is not None and cached[0] == signature:
            return cached[1]
        instance = spec.factory()
        _storage_cache[backend] = (signature, instance)
        return instance


def storage_for_row(row: Any) -> Storage:
    """Resolve a backend from a file row's recorded ``storage`` column."""

    raw = row.get("storage") if hasattr(row, "get") else ""
    name = _normalize_backend_name(raw)
    if storage_registry.get(name) is None:
        if name:
            raise StorageUnavailable("文件记录使用了未注册的存储后端: " + name)
        raise StorageUnavailable("文件记录使用了未注册的存储后端")
    try:
        return get_storage(name)
    except StorageConfigurationError as exc:
        raise StorageUnavailable("文件存储后端不可用: " + name) from exc


# Compatibility aliases used by services and tests.
get_storage_for_row = storage_for_row
build_storage = get_storage
reset_storage_cache = clear_storage_cache
