const state={view:'chat',conversationId:null,tasks:[],memories:[],messages:[],activity:[],offline:false};
let productName='Luma';let tagline='个人助理';
function applyBrand(brand){const name=(brand&&(brand.product_name||brand.name)||'').trim();const nextTagline=brand&&typeof brand.tagline==='string'?brand.tagline.trim():'';if(name)productName=name;if(nextTagline)tagline=nextTagline;document.title=`${productName} · ${tagline}`;const brandName=$('#brandName');if(brandName)brandName.textContent=productName;const brandTagline=$('#brandTagline');if(brandTagline)brandTagline.textContent=tagline;const chatHeading=$('#chatHeading');if(chatHeading)chatHeading.textContent=`和 ${productName} 聊聊`;const memoryHeading=$('#memoryHeading');if(memoryHeading)memoryHeading.textContent=`${productName} 记得什么`}
async function loadBrand(){try{const response=await fetch('/api/v1/brand',{headers:{Accept:'application/json'}});if(response.ok)applyBrand(await response.json())}catch(e){}applyBrand({name:productName,tagline})}
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opts={}){try{const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});if(!r.ok)throw Error(await r.text());return r.json()}catch(e){state.offline=true;return null}}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2500)}
function seed(){state.tasks=[{id:'offline-1',title:'整理本周项目进度',description:'把零散笔记整理成一页简报',status:'in_progress',progress:64,due_at:'今天 18:00'},{id:'offline-2',title:'周五前预约体检',description:'需要你的确认后才会发送预约请求',status:'waiting_approval',progress:30,due_at:'明天'},{id:'offline-3',title:'给家人准备周末行程',description:'收集天气、交通和餐厅选项',status:'queued',progress:8,due_at:'周六'}];state.memories=[{id:'offline-memory-1',kind:'preference',content:'我喜欢先看到 3 个选项，再做决定。'},{id:'offline-memory-2',kind:'fact',content:'我的工作重点是 AI 产品和跨端体验。'},{id:'offline-memory-3',kind:'inferred',content:'我通常在晚上 11 点后不希望被打扰。'}];state.activity=[{time:'今天 09:14',text:`${productName} 从对话中提取了一条待确认记忆`,tag:'MEMORY'},{time:'昨天 18:40',text:'任务「整理本周项目进度」更新为进行中',tag:'TASK'},{time:'昨天 08:30',text:'晨间简报已生成',tag:'BRIEFING'}];state.messages=[{role:'assistant',content:`你好，我是 ${productName}。有什么可以帮你？`,time:'09:15'}]}
async function load(){const data=await api('/dashboard');if(data){state.tasks=data.tasks||[];state.memories=data.memories||[];state.messages=data.messages||[];state.activity=data.activity||[];state.conversationId=data.conversation_id}else seed();render()}
function render(){const pending=state.tasks.filter(t=>t.status!=='done').length;$('#taskCount').textContent=pending;$('#memoryCount').textContent=state.memories.length;$('#conversationCount').textContent=state.messages.length?1:0;$('#briefingTasks').textContent=pending;$('#briefingMemories').textContent=state.memories.length;$('#messageCount').textContent=`${state.messages.length} 条消息`;$('#messages').innerHTML=state.messages.map(m=>`<div class="message ${m.role}"><div class="message-avatar">${m.role==='assistant'?'✦':'L'}</div><div class="bubble"><p>${escapeHtml(m.content).replace(/\n/g,'<br>')}</p><span class="time">${m.time||''}</span>${m.approval?`<div class="inline-card"><div class="card-title">需要你的确认</div><div class="card-desc">${escapeHtml(m.approval)}</div><button class="approve-btn" onclick="approveTask()">确认并继续</button></div>`:''}</div></div>`).join('');$('#focusTasks').innerHTML=state.tasks.slice(0,3).map(t=>`<div class="focus-item"><span class="task-dot ${t.status==='done'?'done':''}"></span><div><div class="item-title">${escapeHtml(t.title)}</div><div class="item-meta">${escapeHtml(t.due_at||'待安排')} · ${statusText(t.status)}</div></div></div>`).join('')||'<div class="item-meta">还没有任务</div>';$('#recentMemory').innerHTML=state.memories.slice(0,3).map(m=>`<div class="memory-item"><strong>${escapeHtml(m.kind||m.category||'MEMORY').toUpperCase()}</strong>${escapeHtml(m.content)}</div>`).join('')||'<div class="item-meta">还没有记忆</div>';$('#missionGrid').innerHTML=state.tasks.map(taskCard).join('')||empty('还没有任务',`把想做的事交给 ${productName}，它会持续跟进。`);$('#memoryGrid').innerHTML=state.memories.map(memoryCard).join('')||empty('还没有记忆','确认后的偏好和事实会出现在这里。');$('#activityList').innerHTML=state.activity.map(a=>`<div class="activity-row"><time>${escapeHtml(a.time)}</time><p>${escapeHtml(a.text)}</p><span class="activity-tag">${escapeHtml(a.tag)}</span></div>`).join('')||empty('还没有活动','完成一次对话后，这里会出现记录。')}
function empty(title,desc){return `<div class="mission-card"><h4>${title}</h4><p>${desc}</p></div>`}function statusText(s){return({todo:'待开始',queued:'待开始',in_progress:'进行中',waiting_approval:'等你确认',done:'已完成',cancelled:'已取消'}[s]||s)}function taskCard(t){const status=statusText(t.status);return `<article class="mission-card ${t.status==='done'?'done':''}"><span class="status">${status.toUpperCase()}</span><h4>${escapeHtml(t.title)}</h4><p>${escapeHtml(t.description||'')}</p><div class="progress"><i style="width:${t.progress||0}%"></i></div><div class="item-meta">${escapeHtml(t.due_at||'未安排')} · ${t.progress||0}%</div></article>`}function memoryCard(m){return `<article class="memory-card"><span class="memory-type">${escapeHtml(m.kind||m.category||'memory').toUpperCase()}</span><p>${escapeHtml(m.content)}</p><button onclick="removeMemory('${m.id}')">删除</button></article>`}
function switchView(view){state.view=view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#chatView').classList.toggle('hidden',view!=='chat');['missions','memory','activity'].forEach(v=>$('#'+v+'View').classList.toggle('hidden',view!==v));$('#viewTitle').innerHTML=({chat:'早上好，Li Wanx <span>☀</span>',missions:'让重要的事持续向前',memory:'你的第二大脑',activity:'每一步都可追溯'}[view])}
async function sendMessage(text){if(!text.trim())return;state.messages.push({role:'user',content:text,time:'现在'});render();$('#composerInput').value='';const local=await api('/conversations/'+(state.conversationId||'default')+'/messages',{method:'POST',body:JSON.stringify({content:text})});if(local?.assistant){state.messages.push(local.assistant);if(local.task)state.tasks.unshift(local.task);if(local.memory)state.memories.unshift(local.memory);state.activity.unshift({time:'刚刚',text:local.activity||'完成了一次对话',tag:local.task?'TASK':'CHAT'});render();return}setTimeout(()=>{const lower=text.toLowerCase();let content='收到。我会把这件事拆成下一步，并在需要你决定时提醒你。';let approval;if(lower.includes('记住')||lower.includes('记得')){const fact=text.replace(/记住|记得/g,'').trim();state.memories.unshift({id:'local-'+Date.now(),kind:'fact',content:fact});content='我可以把它保存为长期记忆，之后会在相关对话里使用。';approval='保存这条记忆？你随时可以在「记忆」里删除。'}if(lower.includes('任务')||lower.includes('提醒')||lower.includes('安排')){const task={id:'local-'+Date.now(),title:text,description:'由对话创建，等待继续拆解',status:'queued',progress:0,due_at:'待安排'};state.tasks.unshift(task);content='我已经把它加入任务列表，接下来会帮你拆解和跟进。'}state.messages.push({role:'assistant',content,time:'刚刚',approval});state.activity.unshift({time:'刚刚',text:'完成了一次对话',tag:'CHAT'});render()},550)}
async function approveTask(){toast(`已确认，${productName} 会继续执行`);const t=state.tasks.find(x=>x.status==='waiting_approval');if(t){t.status='in_progress';render();await api('/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({status:'in_progress'})})}}
async function removeMemory(id){state.memories=state.memories.filter(m=>m.id!==id);render();await api('/memories/'+id,{method:'DELETE'});toast('已删除这条记忆')}
$('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendMessage($('#composerInput').value)});$('#composerInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}});$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));$('#newChat').addEventListener('click',()=>{state.messages=[];state.conversationId=null;state.view='chat';switchView('chat');render();toast('已开始新对话')});$('#addTaskBtn').addEventListener('click',()=>{const title=prompt(`你想让 ${productName} 跟进什么？`);if(title)sendMessage('创建任务：'+title)});$('#addMemoryBtn').addEventListener('click',()=>{const content=prompt(`要让 ${productName} 记住什么？`);if(content){state.memories.unshift({id:'local-'+Date.now(),kind:'fact',content});render();toast('已加入记忆草稿')}});$('#voiceBtn').addEventListener('click',()=>toast('语音入口已准备好，连接移动端后即可使用'));$('#attachBtn').addEventListener('click',()=>toast('可以接入文件、网页或一段上下文'));window.approveTask=approveTask;window.removeMemory=removeMemory;loadBrand().then(load);
